"""Initial migration based on current models

Revision ID: 61fb420c28e7
Revises: 
Create Date: 2025-03-07 02:04:33.605706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61fb420c28e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index('idx_review_content', ['content'], unique=False, mysql_prefix='FULLTEXT')
        batch_op.create_index('idx_reviews_hotel', ['hotel_id'], unique=False)
        batch_op.create_index('idx_reviews_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index('idx_reviews_user')
        batch_op.drop_index('idx_reviews_hotel')
        batch_op.drop_index('idx_review_content', mysql_prefix='FULLTEXT')

    # ### end Alembic commands ###
